FROM php:8.0-apache

# RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
#     && php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
#     && php composer-setup.php \
#     && php -r "unlink('composer-setup.php');"
# 
# RUN mv composer.phar /usr/local/bin/composer
# 
# RUN apt-get update \
# && apt-get install -y \
# git \
# zip \
# unzip \
# vim
# RUN apt-get update \
#     && apt-get install -y libpq-dev \
#     && docker-php-ext-install pdo_mysql pdo_pgsql
# 
# COPY ./ /app/
# ENV COMPOSER_ALLOW_SUPERUSER 1
# ENV COMPOSER_NO_INTERACTION 1 
# RUN cd /app && composer install
# 
# RUN cp -r /app/public/* /var/www/html/
# RUN chown www-data:www-data -R /app

