version: '3.3'
services:
    haruhi:
        build:
            context: ./haruhi
            dockerfile: Dockerfile
        ports:
            - "3124:80"
        hostname: haruhi
        # command: npm run watch
        volumes:
            - ./haruhi:/var/www/html
    yui:
        build:
            context: ./yui
            dockerfile: Dockerfile
        restart: always 
        env_file: ./yui/.db_environment.env
        hostname: yui
        volumes:
         - ./yui:/app
         - db:/var/lib/mysql
    rikka:
        build: ./rikka
        env_file: ./rikka/.env
        volumes:
         - ./rikka:/home/root
        privileged: true
        tty: true
volumes:
    db:

