version: '3.3'
services:
    haruhi:
        build:
            context: ./haruhi
            dockerfile: Dockerfile
        ports:
            - "3124:80"
        hostname: haruhi
        # command: npm run watch
        volumes:
            - ./haruhi:/var/www/html
    eru:
        build:
            context: ./eru
            dockerfile: Dockerfile
        environment:
            - MB_DB_FILE=/metabase-data/metabase.db
        ports:
            - "3000:3000"
        volumes:
            - ./eru/metabase:/metabase-data
    yui:
        build:
            context: ./yui
            dockerfile: Dockerfile
        restart: always 
        env_file: ./yui/.env
        hostname: yui
        volumes:
         - db:/var/lib/mysql
    rikka:
        build: ./rikka
        env_file: ./rikka/.env
        volumes:
         - ./rikka:/home/appuser
        privileged: true
        tty: true
volumes:
    db:

