version: '3.3'
services:
    yui:
        build:
            context: ./yui
            dockerfile: Dockerfile
        restart: always 
        env_file: ./yui/.db_environment.env
        hostname: yui
        volumes:
         - ./yui:/app
         - db:/var/lib/mysql
volumes:
    db:

