
mysql -u root -p${MYSQL_ROOT_PASSWORD} -e"CREATE USER ${DB_MIDAS_ROOT_USER}@'%' IDENTIFIED BY '${DB_MIDAS_ROOT_PASS}';"
mysql -u root -p${MYSQL_ROOT_PASSWORD} -e"CREATE USER ${DB_MIDAS_API_USER}@'%' IDENTIFIED BY '${DB_MIDAS_API_PASS}';"
mysql -u root -p${MYSQL_ROOT_PASSWORD} -e"CREATE USER ${DB_MIDAS_BACKUP_USER}@'%' IDENTIFIED BY '${DB_MIDAS_BACKUP_PASS}';"

mysql -u root -p${MYSQL_ROOT_PASSWORD} -e"GRANT ALL ON ${DB_DATABASE_NAME}.* TO ${DB_MIDAS_ROOT_USER}@'%';"
mysql -u root -p${MYSQL_ROOT_PASSWORD} -e"GRANT GRANT OPTION ON ${DB_DATABASE_NAME}.* TO ${DB_MIDAS_ROOT_USER}@'%';"
mysql -u ${DB_MIDAS_ROOT_USER} -p${DB_MIDAS_ROOT_PASS} -e"GRANT SELECT, INSERT ON ${DB_DATABASE_NAME}.* TO ${DB_MIDAS_API_USER}@'%';"
mysql -u ${DB_MIDAS_ROOT_USER} -p${DB_MIDAS_ROOT_PASS} -e"GRANT SELECT ON ${DB_DATABASE_NAME}.* TO ${DB_MIDAS_BACKUP_USER}@'%';"
